spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: springcloud-demo-test-client5

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: springcloud-demo-config-client-dev
  company.name: example
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: springcloud-demo-test-client

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: springcloud-demo-config-client-beta
  company.name: example
